version: '2'

services:
  db:
    image: mdillon/postgis
  web:
    build: .
    command: ./runserver -h 0.0.0.0 -p 8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
